env:
  node: true
  es6: true
extends: "eslint:recommended"
parserOptions:
  ecmaVersion: 2017
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-trailing-spaces:
    - error
  semi:
    - error
    - always
  camelcase:
    - error
    - properties: never
